Repository Narratium/Narratium.ai, pull requests merged in 2025-07, with the labels that each got.

#51 Update Localization and Enhance Character Download Modal
  app/i18n/locales/en.json
  app/i18n/locales/zh.json
  components/DownloadCharacterModal.tsx
Labels: Review effort 2/5, Possible security concern

#65 feat: add edit preset name & duplicate preset
  app/i18n/locales/en.json
  app/i18n/locales/zh.json
  components/CopyPresetModal.tsx
  components/EditPresetNameModal.tsx
  components/PresetEditor.tsx
Labels: Review effort 2/5

#82 feat: add magician preset and update related components
  README.md
  README_ZH.md
Labels: Review effort 3/5

#89 feat: add cla
  CLA.md
  CONTRIBUTING.md
Labels: Review effort 1/5

#90 Update .env.example
  .env.example
Labels: Review effort 1/5

#95 feat: add husky for precommit
  .husky/pre-commit
  package-lock.json
  package.json
Labels: Review effort 1/5

#96 feat: change errorToast to toast
  app/character/page.tsx
  app/creator-area/page.tsx
  app/i18n/locales/en.json
  app/i18n/locales/zh.json
  components/ErrorToast.tsx
  components/Toast.tsx
Labels: Review effort 2/5
